name: Build Windows App

on:
  workflow_dispatch: # 仅允许你在网页上点击按钮手动触发

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '23'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies in client-viewer
        run: |
          cd ./src/client-viewer
          pnpm install

      - name: Install dependencies in root
        run: pnpm install

      - name: Create empty .env file
        run: echo "VITE_CLIENT_VIEWER_GA_TAG=" > ./src/client-viewer/.env

      - name: Build Windows App (64-bit)
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpm run build:win

      - name: Upload Windows exe
        uses: actions/upload-artifact@v4
        with:
          name: Deskreen-Windows-exe
          path: dist/*.exe
